name: deploy-backend
on:
  workflow_call:
    inputs:
      stage:
        type: string
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deployment
    steps:
      - name: Checkout project
        uses: actions/checkout@master
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20.1
      - name: Build binary
        run: |
          cd pkg && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o main main.go && zip listing-getter.zip main
      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: "eu-west-2"
      - name: Deploy Lambda to AWS
        uses: appleboy/lambda-action@master
        with:
          # gets secrets set in env by `configure-aws-credentials`
          aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          function_name: "listing-getter"
          s3_bucket: "arn:aws:s3:::property-scraping-development-lambda-code"
          s3_key: "listing-getter.zip"
          handler: main
          zip_file: ./pkg/listing-getter.zip