name: deploy-to-prod
permissions:
  id-token: write
  contents: read
on: workflow_dispatch
jobs:
  deploy-to-prod:
    uses: ./.github/workflows/abstractDeploy.yml
    with:
      stage: production
      packages: '["listing-getter", "dynamodb-pusher"]'
    secrets: inherit