name: deploy-to-development
on:
  push:
    branches:
      - main
jobs:
  deploy-to-development:
    uses: ./.github/workflows/abstractDeploy.yml
    with:
      stage: development
    secrets: inherit
